/* Evan Wilson, Braeden Cross, Yukie Zhang
 * Dec 16/22
 * A help class that allows the user to veiw instructions for the game in a menu and exit out of that menu */
package ics4ufinalproject;

/**
 *
 * @author evan-
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        howLbl = new javax.swing.JLabel();
        rightInfo = new javax.swing.JLabel();
        leftInfo = new javax.swing.JLabel();
        rightInfo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(204, 255, 204));

        okBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        howLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        howLbl.setText("How to play");

        rightInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rightInfo.setText("2. Right Arrow key or D = Move right");

        leftInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        leftInfo.setText("1. Left Arrow key  or A = Move Left");

        rightInfo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rightInfo1.setText("3. Up Arrow key or W = Throw cow");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightInfo)
                    .addComponent(rightInfo1)
                    .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(howLbl)
                        .addComponent(leftInfo)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addComponent(okBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howLbl)
                .addGap(59, 59, 59)
                .addComponent(leftInfo)
                .addGap(18, 18, 18)
                .addComponent(rightInfo)
                .addGap(18, 18, 18)
                .addComponent(rightInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(okBtn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        //Cose the help window when the ok button is pressed
        dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel howLbl;
    private javax.swing.JLabel leftInfo;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel rightInfo;
    private javax.swing.JLabel rightInfo1;
    // End of variables declaration//GEN-END:variables
}
