/* Evan Wilson, Braeden Cross, Yukie Zhang
 * Dec 16/22
 * A leaderboard class that allows the user to the top player menu and exit out of that menu */
package ics4ufinalproject;

/**
 *
 * @author evan-
 */
public class LeaderBoard extends javax.swing.JFrame {

    /**
     * Creates new form leaderBoard
     */
    public LeaderBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        topPlayerHeader = new javax.swing.JLabel();
        topPlayerLbl = new javax.swing.JLabel();
        topPlayerOkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(204, 255, 255));

        topPlayerHeader.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        topPlayerHeader.setText("Top player:");

        topPlayerLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        topPlayerLbl.setText("There is not a top player yet!");

        topPlayerOkBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        topPlayerOkBtn.setText("Ok");
        topPlayerOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topPlayerOkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(topPlayerHeader))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topPlayerLbl)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addComponent(topPlayerOkBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPlayerHeader)
                .addGap(82, 82, 82)
                .addComponent(topPlayerLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(topPlayerOkBtn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topPlayerOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topPlayerOkBtnActionPerformed
        //Cose the leader board window when the ok button is pressed
        dispose();
    }//GEN-LAST:event_topPlayerOkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel topPlayerHeader;
    private javax.swing.JLabel topPlayerLbl;
    private javax.swing.JButton topPlayerOkBtn;
    // End of variables declaration//GEN-END:variables
}
