/* Evan Wilson, Braeden Cross, Yukie Zhang
 * Dec 16/22
 * A main class for our space invaders program that allows the user to naviage the main menu */
package ics4ufinalproject;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        leaderBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        gameNameLbl = new javax.swing.JLabel();
        bagLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        leaderBtn.setBackground(new java.awt.Color(255, 153, 153));
        leaderBtn.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        leaderBtn.setText("LeaderBoard");
        leaderBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBtnActionPerformed(evt);
            }
        });
        jPanel2.add(leaderBtn);
        leaderBtn.setBounds(0, 250, 160, 50);

        playBtn.setBackground(new java.awt.Color(204, 255, 204));
        playBtn.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        playBtn.setText("Play");
        playBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        jPanel2.add(playBtn);
        playBtn.setBounds(420, 250, 160, 50);

        helpBtn.setBackground(new java.awt.Color(204, 255, 204));
        helpBtn.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        helpBtn.setText("Help");
        helpBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });
        jPanel2.add(helpBtn);
        helpBtn.setBounds(420, 310, 160, 50);

        exitBtn.setBackground(new java.awt.Color(255, 153, 153));
        exitBtn.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn);
        exitBtn.setBounds(0, 310, 160, 50);

        gameNameLbl.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        gameNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        gameNameLbl.setText("Welcome to Ship Invaders");
        gameNameLbl.setAlignmentY(0.0F);
        jPanel2.add(gameNameLbl);
        gameNameLbl.setBounds(30, 0, 530, 50);

        bagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ics4ufinalproject/spaceBackground.jpg"))); // NOI18N
        bagLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(bagLbl);
        bagLbl.setBounds(0, 0, 580, 629);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBtnActionPerformed
        //Open a new leaderboard window if leaderboard is pressed
        new LeaderBoard().setVisible(true);
    }//GEN-LAST:event_leaderBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        
    }//GEN-LAST:event_playBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        //Open a new help window if leaderboard is pressed
        new Help().setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        //If the user presses the exit button
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bagLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gameNameLbl;
    private javax.swing.JButton helpBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton leaderBtn;
    private javax.swing.JButton playBtn;
    // End of variables declaration//GEN-END:variables
}
